version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: jobtracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_tracker_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jobtracker-net

  backend:
    build: ./job-tracker-backend
    container_name: jobtracker-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job_tracker_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - jobtracker-net

  frontend:
    build: ./job-tracker-frontend
    container_name: jobtracker-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/api/jobs
    networks:
      - jobtracker-net

networks:
  jobtracker-net:

volumes:
  mysql_data:
